export type LocaleId = "en" | "ru";

export const labels = {
  en: {
    name: "HANDOFF",
    model: "HANDOFF-1.1",
    tagline: "Previous session → next session. Memory of junctions, not a path forecast.",
    awaiting: "Awaiting",
    live: "In session",
    continue: "Continue",
    break: "Break",
    unclear: "Unclear",
    wait: "Wait",
    inside: "Inside",
    brokeHigh: "Broke high",
    brokeLow: "Broke low",
    both: "Both",
    stuck: "Stuck",
    pressedHigh: "Pressed high",
    pressedLow: "Pressed low",
    stretch: "Stretch",
    closeLoc: "Close loc",
    sweep: "Sweep",
    prior: "Prior session",
    memory: "Memory",
    thin: "Thin sample — do nothing from this card.",
    n: "n",
    ticks: "Last 24 junctions",
    footer: "Filter, not order. Memory is session geometry only. Neighbors are not in the bucket.",
    rule: "Session junction. Do not pick a side from this layer while awaiting / unclear / thin / stuck or n < 40.",
    demo: "Demo feed",
    liveFeed: "Live pit",
    symbol: "Symbol",
    venue: "Venue",
    lookback: "Lookback",
    locale: "Locale",
    open: "Open",
    high: "High",
    low: "Low",
    close: "Close",
    loading: "Reading the last junction…",
    error: "Could not load the card. Retrying.",
    neighbors: "Siblings (display only)",
    deadZone: "Dead zone",
    weekend: "Weekend",
    exportJson: "Export JSON",
    exportCsv: "Export CSV",
    schema: "Schema",
  },
  ru: {
    name: "HANDOFF",
    model: "HANDOFF-1.1",
    tagline: "Прошлая сессия → следующая. Память стыков, не прогноз пути.",
    awaiting: "Ожидание",
    live: "В сессии",
    continue: "Continue",
    break: "Break",
    unclear: "Unclear",
    wait: "Ждать",
    inside: "Inside",
    brokeHigh: "Broke high",
    brokeLow: "Broke low",
    both: "Both",
    stuck: "Stuck",
    pressedHigh: "Pressed high",
    pressedLow: "Pressed low",
    stretch: "Stretch",
    closeLoc: "Close loc",
    sweep: "Sweep",
    prior: "Прошлая сессия",
    memory: "Память",
    thin: "Тонкая выборка — с этой карточки ничего не делать.",
    n: "n",
    ticks: "Последние 24 стыка",
    footer: "Фильтр, не приказ. Память — только геометрия сессии. Соседи не в ключе корзины.",
    rule: "Стык сессий. Сторону из этого слоя не выбирать, пока awaiting / unclear / thin / stuck или n < 40.",
    demo: "Демо поток",
    liveFeed: "Живой пит",
    symbol: "Символ",
    venue: "Пит",
    lookback: "Lookback",
    locale: "Язык",
    open: "Open",
    high: "High",
    low: "Low",
    close: "Close",
    loading: "Читаю последний стык…",
    error: "Карточка не загрузилась. Повтор.",
    neighbors: "Соседи (только показ)",
    deadZone: "Мёртвая зона",
    weekend: "Выходной",
    exportJson: "Экспорт JSON",
    exportCsv: "Экспорт CSV",
    schema: "Схема",
  },
} as const;
